// 小说平台推广达人中心数据
export interface PlatformInfo {
  id: string;
  name: string;
  brand: string;
  description: string;
  platforms: string[];
  categories: string[];
  urls: { label: string; url: string }[];
  highlights: string[];
  tips: string[];
  features: string[];
  contact: { email?: string; phone?: string; wechat?: string };
  audience: string;
  joinTips: string;
  commissionRate: string;
  publishFlow: { step: number; title: string; description: string }[];
}

export const PLATFORMS: PlatformInfo[] = [
  {
    id: 'qidian',
    name: '起点读书',
    brand: '阅文集团',
    description: '中国最大的正版网络文学平台之一，拥有海量原创作者资源和完整的推广达人体系。起点读书的达人中心支持阅读推广、书评分享、书单推荐等多种变现方式。',
    platforms: ['iOS', 'Android', 'Web', 'iPad'],
    categories: ['玄幻', '都市', '科幻', '历史', '言情', '仙侠', '军事', '游戏', '竞技', '现实', '悬疑', '轻小说'],
    urls: [
      { label: '起点达人中心', url: 'https://www.qidian.com/author/' },
      { label: '作者入驻', url: 'https://author.qidian.com/' },
      { label: '推广计划', url: 'https://www.qidian.com/' },
      { label: '作家助手 App', url: 'https://www.qidian.com/' },
    ],
    highlights: ['大神作者签约', '月票榜推广', '年度作家榜', '新人创作扶持'],
    tips: ['阅读量高的作品分成比例更优', '书评达人月榜可获得官方推荐位', '新书可申请官方推荐位'],
    features: ['作者端 App', '大数据推荐', '电子版权', '有声书合作', '影视IP开发'],
    contact: { email: 'contact@qidian.com' },
    audience: '原创作者、书评达人、推广机构',
    joinTips: '注册起点账号后在作者中心申请成为签约作者',
    commissionRate: '50%-70% 分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册起点账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交至少3000字正文进行审核' },
      { step: 4, title: '审核通过', description: '审核通过后作品正式上架' },
      { step: 5, title: '持续更新', description: '每日更新章节，参与推荐位申请' },
      { step: 6, title: '签约申请', description: '作品成绩达标后可申请签约' },
      { step: 7, title: '获得收益', description: '签约后获得订阅分成、打赏等收益' },
    ],
  },
  {
    id: 'fanqie',
    name: '番茄小说',
    brand: '抖音集团 / 字节跳动',
    description: '抖音旗下的免费阅读平台，背靠字节跳动的流量和技术优势，番茄小说的推广达人计划整合了抖音短视频推广能力，达人可获得丰厚的广告分成和推广奖励。',
    platforms: ['iOS', 'Android', 'Web', '抖音小程序'],
    categories: ['都市', '玄幻', '历史', '言情', '脑洞', '悬疑', '科幻', '二次元', '轻小说', '体育'],
    urls: [
      { label: '番茄小说官网', url: 'https://fanqienovel.com/' },
      { label: '番茄作家助手', url: 'https://fanqienovel.com/' },
      { label: '作者签约入口', url: 'https://fanqienovel.com/' },
      { label: '抖音达人推广', url: 'https://creator.douyin.com/' },
      { label: '巨量引擎合作', url: 'https://e.oceanengine.com/' },
    ],
    highlights: ['免费小说阅读', '短视频联合推广', '全勤奖励丰厚', '作品影视化机会多'],
    tips: ['抖音流量加持更容易爆', '新人也有机会拿到官方推广位', '番茄的全勤奖力度大'],
    features: ['免费阅读模式', '广告分成', '短视频联动', 'AI推荐系统', 'IP衍生开发'],
    contact: { email: 'contact@fanqienovel.com' },
    audience: '原创作者、抖音达人、短视频创作者',
    joinTips: '注册番茄账号后下载番茄作家助手App申请签约',
    commissionRate: '全勤 + 广告分成 + 推广奖励',
    publishFlow: [
      { step: 1, title: '注册账号', description: '注册番茄小说账号，登录作家中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文进行审核（一般1-3天）' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架，开始获得广告分成' },
      { step: 5, title: '持续更新', description: '每日更新，参与全勤奖' },
      { step: 6, title: '签约申请', description: '作品达标后申请独家签约' },
      { step: 7, title: '抖音推广', description: '通过抖音短视频推广作品，获得额外奖励' },
    ],
  },
  {
    id: 'qimao',
    name: '七猫中文网',
    brand: '七猫文化传媒',
    description: '国内领先的中文免费阅读平台，拥有完整的作者招募体系和推广达人合作计划。七猫的推广平台与微信生态深度整合，适合朋友圈/公众号等私域推广。',
    platforms: ['iOS', 'Android', 'Web', '微信公众号', '微信小程序'],
    categories: ['都市', '玄幻', '言情', '历史', '军事', '悬疑', '科幻', '同人'],
    urls: [
      { label: '七猫中文网', url: 'https://www.qimao.com/' },
      { label: '作者入驻通道', url: 'https://author.qimao.com/' },
      { label: '推广达人中心', url: 'https://www.qimao.com/' },
      { label: '合作推广计划', url: 'https://www.qimao.com/' },
    ],
    highlights: ['免费阅读模式', '微信生态整合', '私域推广分成', 'AI技术辅助创作'],
    tips: ['七猫的分成机制对新人友好', '私域流量推广效果明显', '与公众号联动是优势'],
    features: ['免费阅读', '广告分成', '微信推广', '作者社区', '免费创作工具'],
    contact: { email: 'bd@qimao.com' },
    audience: '原创作者、自媒体人、微信公众号运营者',
    joinTips: '通过七猫中文网作者入驻通道注册并签约',
    commissionRate: '40%-60% 广告分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册七猫账号，登录作者后台' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，等待结果' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架' },
      { step: 5, title: '持续更新', description: '每日更新，参与全勤奖励' },
      { step: 6, title: '私域推广', description: '通过微信公众号、朋友圈推广作品' },
      { step: 7, title: '获得收益', description: '广告分成 + 推广奖励' },
    ],
  },
  {
    id: 'zongheng',
    name: '纵横中文网',
    brand: '百度集团 / 完美世界',
    description: '老牌网络文学平台，由完美世界和百度联合运营。纵横中文网拥有完善的作者签约体系和推广达人计划，尤其在男频网文领域有深厚积累。',
    platforms: ['iOS', 'Android', 'Web', 'iPadOS'],
    categories: ['玄幻', '奇幻', '都市', '历史', '军事', '科幻', '游戏', '竞技', '同人', '二次元'],
    urls: [
      { label: '纵横中文网', url: 'https://www.zongheng.com/' },
      { label: '作者中心', url: 'https://author.zongheng.com/' },
      { label: '签约申请', url: 'https://www.zongheng.com/' },
      { label: '推广合作', url: 'https://www.zongheng.com/' },
    ],
    highlights: ['老牌平台口碑好', '男频资源强', '作者奖励稳定', '与百度搜索联动'],
    tips: ['纵横在男频读者中认可度高', '大神作家资源丰富', '百度搜索流量加持'],
    features: ['作者社区', '月度榜单', '大神计划', '有声书开发', '漫画改编'],
    contact: { email: 'contact@zongheng.com' },
    audience: '原创作者、资深网文读者、男频推广达人',
    joinTips: '在纵横作者中心注册后提交签约申请',
    commissionRate: '签约作者 50%-80% 分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册纵横账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核（男频作品优先审核）' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架纵横中文网' },
      { step: 5, title: '持续更新', description: '每日更新章节，参与纵横榜单' },
      { step: 6, title: '签约申请', description: '作品成绩达标后申请签约' },
      { step: 7, title: '百度联动', description: '签约后获得百度搜索流量加持' },
    ],
  },
  {
    id: 'jjwxc',
    name: '晋江文学城',
    brand: '晋江原创',
    description: '国内最具影响力的女频文学原创平台，晋江文学城以高品质的原创言情、纯爱、同人作品闻名，是女频作者首选的发表平台之一。晋江的推广体系与读者深度绑定。',
    platforms: ['iOS', 'Android', 'Web', 'iPadOS'],
    categories: ['言情', '纯爱', '原创', '同人', '古代言情', '现代言情', '幻想言情', '未来架空'],
    urls: [
      { label: '晋江文学城', url: 'https://www.jjwxc.net/' },
      { label: '作者申请', url: 'https://www.jjwxc.net/register.php' },
      { label: '读者推广计划', url: 'https://www.jjwxc.net/' },
      { label: 'VIP 作品中心', url: 'https://www.jjwxc.net/' },
    ],
    highlights: ['女频文学领头羊', '读者付费意愿高', '作品IP开发丰富', '社区氛围浓厚'],
    tips: ['晋江的读者忠诚度高', 'V文订阅分成可长期收益', '同人作品在晋江有特色优势'],
    features: ['VIP订阅', '评论互动', '作者专栏', '编辑签约', '作品排行榜'],
    contact: { email: 'help@jjwxc.com' },
    audience: '女频作者、纯爱创作者、言情推广达人',
    joinTips: '注册晋江账号后申请成为作者并签约',
    commissionRate: '订阅分成 + 霸王票等奖励',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册晋江账号，申请成为作者' },
      { step: 2, title: '创建文章', description: '填写文章标题、文案，选择文章类型' },
      { step: 3, title: '发布文章', description: '发布正文，设置标签和文案风格' },
      { step: 4, title: '读者互动', description: '回复评论，建立读者粘性' },
      { step: 5, title: '申请V文', description: '作品达到条件后申请VIP订阅' },
      { step: 6, title: '签约编辑', description: '与晋江编辑签约，获得推荐资源' },
      { step: 7, title: '收益分成', description: '获得订阅分成、霸王票等收益' },
    ],
  },
  {
    id: 'feilu',
    name: '飞卢小说网',
    brand: '飞卢信息科技',
    description: '以读者投稿和快速更新著称的网文平台，飞卢的推广达人体系非常完善，特别适合脑洞文、爽文类作品的推广。飞卢的分成机制对新人作者非常友好。',
    platforms: ['iOS', 'Android', 'Web'],
    categories: ['都市', '玄幻', '脑洞', '同人', '科幻', '历史', '网游', '动漫', '轻小说'],
    urls: [
      { label: '飞卢小说网', url: 'https://b.faloo.com/' },
      { label: '作者中心', url: 'https://b.faloo.com/author/' },
      { label: '飞卢推广', url: 'https://b.faloo.com/' },
      { label: '推广达人', url: 'https://b.faloo.com/' },
    ],
    highlights: ['读者投稿量大', '更新速度快', '新人友好', '分成机制透明'],
    tips: ['飞卢的读者对脑洞文接受度高', '推荐榜单位置对新人友好', '日更新量影响排名'],
    features: ['日更新推荐', '读者投票', '榜单系统', '订阅分成', '作者社区'],
    contact: { email: 'service@faloo.com' },
    audience: '脑洞文作者、爽文创作者、快速更新达人',
    joinTips: '注册飞卢账号后在作者中心申请签约',
    commissionRate: '45%-65% 订阅分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册飞卢账号，登录作者后台' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '快速更新', description: '提交至少3章正文，开始日更' },
      { step: 4, title: '审核上架', description: '审核通过后作品上架，进入榜单' },
      { step: 5, title: '读者投票', description: '参与飞卢读者投票，提升排名' },
      { step: 6, title: '签约申请', description: '更新稳定后申请签约' },
      { step: 7, title: '分成收益', description: '获得订阅分成，快速更新有额外奖励' },
    ],
  },
  {
    id: 'shuqi',
    name: '书旗小说',
    brand: '阿里巴巴 / 阿里文学',
    description: '阿里文学旗下的阅读品牌，书旗小说的推广达人计划与阿里电商生态深度绑定，达人不仅可以推广作品，还能通过淘宝、天猫等渠道实现多场景变现。',
    platforms: ['iOS', 'Android', 'Web', '淘宝', 'UC浏览器'],
    categories: ['都市', '玄幻', '言情', '历史', '科幻', '军事', '悬疑', '二次元', '游戏', '同人'],
    urls: [
      { label: '书旗小说官网', url: 'https://www.shuqi.com/' },
      { label: '阿里文学合作', url: 'https://www.shuqi.com/' },
      { label: '作者入驻', url: 'https://www.shuqi.com/' },
      { label: 'UC推广计划', url: 'https://www.uc.cn/' },
    ],
    highlights: ['阿里生态资源', '多渠道流量入口', '淘宝推广联动', 'UC浏览器加持'],
    tips: ['书旗可通过淘宝、UC等多端入口获得流量', '阿里生态推广分成叠加收益', '适合电商+小说的跨界推广'],
    features: ['阿里电商联动', 'UC信息流', '多媒体合作', '内容电商', 'IP衍生'],
    contact: { email: 'service@aliwenxue.com' },
    audience: '原创作者、电商达人、内容创作者',
    joinTips: '在书旗小说官网的作者入口注册并签约',
    commissionRate: '50%-70% + 电商推广收益',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册书旗账号，登录阿里文学作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，等待结果' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架书旗小说' },
      { step: 5, title: '持续更新', description: '每日更新章节，参与阿里文学榜单' },
      { step: 6, title: '电商联动', description: '通过淘宝、UC等渠道推广作品' },
      { step: 7, title: '多元收益', description: '获得订阅分成 + 电商推广收益' },
    ],
  },
  {
    id: '17k',
    name: '17K 小说网',
    brand: '中文在线',
    description: '中文在线旗下的大型原创文学平台，17K小说网拥有完善的作者培养体系和推广达人计划。17K特别注重对新人作者的扶持，提供从创作培训到签约推广的一条龙服务。',
    platforms: ['iOS', 'Android', 'Web', 'iPadOS'],
    categories: ['都市', '玄幻', '历史', '军事', '科幻', '言情', '游戏', '竞技', '悬疑', '同人'],
    urls: [
      { label: '17K 小说网', url: 'https://www.17k.com/' },
      { label: '作者签约', url: 'https://author.17k.com/' },
      { label: '推广中心', url: 'https://www.17k.com/' },
      { label: '网大公开课', url: 'https://www.17k.com/' },
    ],
    highlights: ['新人扶持力度大', '作者培训体系完善', '中文在线资源', 'IP孵化成熟'],
    tips: ['17K的网大公开课免费教写作', '新人福利体系完善', '适合从零基础起步'],
    features: ['作者培训', '网大公开课', '编辑指导', '全勤奖励', 'IP开发'],
    contact: { email: 'service@17k.com' },
    audience: '新人作者、网文爱好者、培训学员',
    joinTips: '注册17K账号后在作者中心申请签约',
    commissionRate: '50%-70% 作品分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册17K账号，登录作者中心' },
      { step: 2, title: '新人培训', description: '参加网大公开课，学习写作技巧' },
      { step: 3, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 4, title: '提交审核', description: '提交正文审核，编辑一对一指导' },
      { step: 5, title: '审核通过', description: '审核通过后作品上架17K小说网' },
      { step: 6, title: '新人扶持', description: '参与新人福利计划，获得推荐资源' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得分成收益' },
    ],
  },
  {
    id: 'yuewen',
    name: '阅文作家专区',
    brand: '阅文集团',
    description: '阅文集团旗下统一的作者服务平台，涵盖起点、创世、云起、潇湘书院等多个子品牌的作者服务。阅文的推广达人体系提供跨平台的推广能力和IP开发机会。',
    platforms: ['iOS', 'Android', 'Web', '作家助手'],
    categories: ['男频', '女频', '青春', '玄幻', '都市', '科幻', '历史', '军事', '游戏', '竞技', '悬疑', '体育', '现实', '轻小说'],
    urls: [
      { label: '阅文作家专区', url: 'https://yc.qq.com/' },
      { label: '作家助手', url: 'https://www.qidian.com/' },
      { label: '作家培训计划', url: 'https://yc.qq.com/' },
      { label: 'IP 开发合作', url: 'https://yc.qq.com/' },
      { label: '微信读书推广', url: 'https://weread.qq.com/' },
      { label: 'QQ阅读', url: 'https://ubook.qq.com/' },
    ],
    highlights: ['国内最大文学IP库', '影视化改编机会多', '腾讯生态资源', '多平台联动'],
    tips: ['阅文的IP开发体系成熟，优秀作品有机会影视化', '腾讯系流量加持', '作家助手提供全场景创作体验'],
    features: ['多平台联动', '作家助手', 'IP开发', '影视化', '有声书', '漫画改编'],
    contact: { email: 'author@yuewen.com' },
    audience: '原创作者、IP开发者、内容创业者',
    joinTips: '通过阅文作家专区或作家助手App申请签约',
    commissionRate: '50%-75% 分成 + IP收益',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册阅文账号，登录作家专区' },
      { step: 2, title: '选择平台', description: '根据作品类型选择起点/创世/云起等子平台' },
      { step: 3, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 4, title: '提交审核', description: '提交正文审核，等待结果' },
      { step: 5, title: '多平台分发', description: '审核通过后作品在阅文全平台分发' },
      { step: 6, title: 'IP开发', description: '优秀作品获得影视化、有声书等IP开发机会' },
      { step: 7, title: '多元收益', description: '获得订阅分成 + IP收益 + 全勤奖励' },
    ],
  },
  {
    id: 'chuangshi',
    name: '创世中文网',
    brand: '阅文集团 / 腾讯',
    description: '阅文集团旗下的综合性原创文学平台，创世中文网的作者招募和推广体系与QQ阅读、微信读书等腾讯系产品深度整合，推广达人可获得多端流量加持。',
    platforms: ['iOS', 'Android', 'Web', '微信读书', 'QQ阅读'],
    categories: ['玄幻', '都市', '历史', '军事', '科幻', '游戏', '竞技', '现实', '悬疑', '言情', '同人'],
    urls: [
      { label: '创世中文网', url: 'https://chuangshi.qq.com/' },
      { label: '作者中心', url: 'https://chuangshi.qq.com/' },
      { label: '推广计划', url: 'https://chuangshi.qq.com/' },
      { label: 'QQ阅读推广', url: 'https://ubook.qq.com/' },
    ],
    highlights: ['腾讯生态加持', '微信读书联动', 'QQ阅读流量', '新人作者友好'],
    tips: ['创世在男频都市和游戏文方面有优势', '腾讯系产品引流效果明显', '适合与微信生态结合推广'],
    features: ['腾讯生态', '多端阅读', '榜单系统', '作者社区', '编辑签约'],
    contact: { email: 'contact@chuangshi.qq.com' },
    audience: '男频作者、腾讯生态推广达人',
    joinTips: '注册创世中文网账号后在作者中心申请签约',
    commissionRate: '50%-70% 作品分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册创世账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，等待结果' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架创世中文网' },
      { step: 5, title: '腾讯分发', description: '作品分发到QQ阅读、微信读书等腾讯系产品' },
      { step: 6, title: '持续更新', description: '每日更新章节，参与榜单竞争' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得分成收益' },
    ],
  },
  {
    id: 'yunqi',
    name: '云起书院',
    brand: '阅文集团',
    description: '阅文集团旗下的女频原创文学平台，云起书院专注于为女性读者和作者服务，提供从创作、编辑到推广、签约、分成的一条龙服务，女频资源丰富。',
    platforms: ['iOS', 'Android', 'Web'],
    categories: ['言情', '玄幻言情', '古代言情', '现代言情', '浪漫青春', '科幻未来', '悬疑推理', '同人'],
    urls: [
      { label: '云起书院', url: 'https://yunqi.qq.com/' },
      { label: '作者入驻', url: 'https://yunqi.qq.com/' },
      { label: '推广计划', url: 'https://yunqi.qq.com/' },
      { label: 'VIP签约', url: 'https://yunqi.qq.com/' },
    ],
    highlights: ['女频文学专业平台', '言情资源丰富', '读者付费意愿强', '编辑资源完善'],
    tips: ['云起在古言、现言、青春言情领域有深厚积累', '言情读者付费习惯好', '编辑一对一指导'],
    features: ['VIP订阅', '作者专栏', '女频推广', '编辑指导', '言情IP开发'],
    contact: { email: 'service@yunqi.qq.com' },
    audience: '女频作者、言情作家、青春文学推广达人',
    joinTips: '在云起书院作者入口注册并签约',
    commissionRate: '50%-70% 分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册云起账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面（言情风格优先）' },
      { step: 3, title: '提交审核', description: '提交正文审核，等待女频编辑审核' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架云起书院' },
      { step: 5, title: '持续更新', description: '每日更新章节，参与女频榜单' },
      { step: 6, title: '编辑指导', description: '获得编辑一对一指导，优化内容' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得订阅分成' },
    ],
  },
  {
    id: 'hongxiu',
    name: '红袖读书',
    brand: '阅文集团',
    description: '专注于女性文学的在线阅读平台，红袖读书汇集了大量原创言情、都市、古代、悬疑等作品，是女频作者推广作品的重要渠道之一，推广体系完善。',
    platforms: ['iOS', 'Android', 'Web'],
    categories: ['言情', '都市', '古代', '现代', '悬疑', '玄幻', '奇幻', '同人'],
    urls: [
      { label: '红袖读书', url: 'https://www.hongxiu.com/' },
      { label: '作者入驻', url: 'https://www.hongxiu.com/' },
      { label: '推广中心', url: 'https://www.hongxiu.com/' },
      { label: 'VIP作品', url: 'https://www.hongxiu.com/' },
    ],
    highlights: ['女性读者为主', '言情作品资源丰富', '订阅分成稳定', '社区氛围活跃'],
    tips: ['红袖读书的言情读者群体稳定', '订阅分成适合长期收益', '作者社区活跃，可互相推广'],
    features: ['VIP订阅', '读者评论', '作者社区', '订阅分成', '榜单推荐'],
    contact: { email: 'service@hongxiu.com' },
    audience: '女频作者、言情推广达人',
    joinTips: '注册红袖读书账号后在作者中心申请签约',
    commissionRate: '45%-65% 订阅分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册红袖账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，等待结果' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架红袖读书' },
      { step: 5, title: '社区互动', description: '参与作者社区，与读者互动' },
      { step: 6, title: '持续更新', description: '每日更新章节，参与红袖榜单' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得订阅分成' },
    ],
  },
  {
    id: 'xiaoxiang',
    name: '潇湘书院',
    brand: '阅文集团',
    description: '历史悠久的女频原创文学平台，潇湘书院以古代言情和宫斗文闻名。潇湘书院的推广体系与阅文集团资源深度整合，提供从签约、推广到IP开发的全流程服务。',
    platforms: ['iOS', 'Android', 'Web'],
    categories: ['古代言情', '宫斗', '玄幻言情', '现代言情', '穿越', '重生', '历史', '悬疑推理'],
    urls: [
      { label: '潇湘书院', url: 'https://www.xxsy.net/' },
      { label: '作者中心', url: 'https://www.xxsy.net/' },
      { label: '推广计划', url: 'https://www.xxsy.net/' },
      { label: '签约申请', url: 'https://www.xxsy.net/' },
    ],
    highlights: ['女频老牌平台', '古言宫斗特色', '阅文资源加持', '读者忠诚度高'],
    tips: ['潇湘书院的古言读者非常专业', '宫斗、权谋文在潇湘有天然优势', '编辑对新人有耐心指导'],
    features: ['VIP订阅', '作者社区', '编辑指导', '榜单推荐', 'IP孵化'],
    contact: { email: 'service@xxsy.net' },
    audience: '古言作者、宫斗权谋文作者、女频推广达人',
    joinTips: '在潇湘书院作者入口注册后申请签约',
    commissionRate: '50%-70% 作品分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册潇湘账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类（古言宫斗优先），上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，古言编辑专项审核' },
      { step: 4, title: '审核通过', description: '审核通过后作品上架潇湘书院' },
      { step: 5, title: '持续更新', description: '每日更新章节，参与古言榜单' },
      { step: 6, title: 'IP孵化', description: '优秀古言作品获得IP孵化机会' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得分成收益' },
    ],
  },
  {
    id: 'haokan',
    name: '好看小说',
    brand: '阅文集团',
    description: '阅文集团旗下的全品类小说阅读平台，好看小说提供简洁的阅读体验和多维度的推广体系，特别适合新人作者尝试网络文学创作，推广门槛低。',
    platforms: ['iOS', 'Android', 'Web'],
    categories: ['全品类', '都市', '玄幻', '言情', '历史', '科幻', '悬疑', '游戏', '竞技'],
    urls: [
      { label: '好看小说', url: 'https://www.haokan.com/' },
      { label: '作者入驻', url: 'https://www.haokan.com/' },
      { label: '推广计划', url: 'https://www.haokan.com/' },
    ],
    highlights: ['全品类覆盖', '新人友好', '推广门槛低', '简洁阅读体验'],
    tips: ['好看小说适合快速试水网络文学', '推广门槛不高，新人容易起步', '全品类覆盖可尝试不同题材'],
    features: ['全品类收录', '简洁界面', '推广入口', '作者服务', '榜单推荐'],
    contact: { email: 'service@haokan.com' },
    audience: '新人作者、全品类推广达人',
    joinTips: '在好看小说官网的作者入口注册并签约',
    commissionRate: '40%-60% 作品分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册好看小说账号，登录作者中心' },
      { step: 2, title: '创建作品', description: '填写书名、简介、分类，上传封面' },
      { step: 3, title: '提交审核', description: '提交正文审核，审核门槛低' },
      { step: 4, title: '快速上架', description: '审核通过后作品快速上架' },
      { step: 5, title: '全品类尝试', description: '可尝试不同题材，灵活调整方向' },
      { step: 6, title: '持续更新', description: '每日更新章节，积累读者' },
      { step: 7, title: '签约分成', description: '作品达标后签约，获得分成收益' },
    ],
  },
  {
    id: 'zhuishu',
    name: '追书神器',
    brand: '追书神器',
    description: '追书神器是国内用户量最大的小说搜索和阅读工具之一。其开放平台允许第三方开发者和推广达人接入搜索API，实现小说内容的聚合推广。适合做小说搜索类产品。',
    platforms: ['iOS', 'Android', 'Web', '开放 API'],
    categories: ['全品类搜索', '玄幻', '都市', '言情', '历史', '科幻', '军事', '悬疑', '游戏', '竞技', '轻小说', '同人'],
    urls: [
      { label: '追书神器官网', url: 'https://www.zhuishushenqi.com/' },
      { label: 'API 开放平台', url: 'https://api.zhuishushenqi.com/' },
      { label: '作者中心', url: 'https://www.zhuishushenqi.com/' },
      { label: '推广合作', url: 'https://www.zhuishushenqi.com/' },
    ],
    highlights: ['聚合搜索能力强', '开放API接口', '海量书籍收录', '用户基数大'],
    tips: ['追书神器的API适合做搜索推广类产品', '用户量大但需注意版权问题', '建议结合原创内容推广'],
    features: ['小说搜索', '开放API', '阅读推荐', '排行榜'],
    contact: { email: 'contact@zhuishushenqi.com' },
    audience: '开发者、搜索推广达人、API接入者',
    joinTips: '通过追书神器开放平台申请API接入',
    commissionRate: '按API调用计费/合作分成',
    publishFlow: [
      { step: 1, title: '注册登录', description: '注册追书神器账号，登录开放平台' },
      { step: 2, title: 'API申请', description: '申请API接入权限，获取API密钥' },
      { step: 3, title: '技术接入', description: '接入追书神器搜索API，开发应用' },
      { step: 4, title: '内容聚合', description: '聚合小说内容，提供搜索服务' },
      { step: 5, title: '推广运营', description: '推广应用，获取用户流量' },
      { step: 6, title: '流量变现', description: '通过API调用计费和合作分成变现' },
      { step: 7, title: '持续优化', description: '优化搜索体验，提升用户留存' },
    ],
  },
];

// 短剧平台推广达人数据
export interface ShortDramaPlatformInfo {
  id: string;
  name: string;
  brand: string;
  description: string;
  platforms: string[];
  categories: string[];
  urls: { label: string; url: string }[];
  highlights: string[];
  tips: string[];
  features: string[];
  contact: { email?: string; phone?: string; wechat?: string };
  audience: string;
  joinTips: string;
  commissionRate: string;
  bonus: string;
  publishFlow: { step: number; title: string; description: string }[];
}

export const SHORT_DRAMA_PLATFORMS: ShortDramaPlatformInfo[] = [
  {
    id: 'douyin-shortdrama',
    name: '抖音短剧',
    brand: '字节跳动',
    description: '抖音是国内最大的短视频平台之一，短剧内容在抖音有着巨大的流量池。抖音短剧推广达人可通过星图平台、达人接单、广告分成等多种方式获得收益。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['都市情感', '玄幻修真', '甜宠', '虐恋', '复仇', '霸总', '古装', '悬疑', '搞笑', '校园'],
    urls: [
      { label: '抖音创作者中心', url: 'https://creator.douyin.com/' },
      { label: '星图平台', url: 'https://www.xingtaodata.com/' },
      { label: '抖音短剧官方', url: 'https://www.douyin.com/' },
      { label: '巨量星图达人', url: 'https://star.toutiao.com/' },
    ],
    highlights: ['星图接单变现', '短剧分账', '广告植入', '直播带货联动'],
    tips: ['抖音短剧3-5分钟最受欢迎', '前3秒决定完播率', '剧情反转要有爆点', '配合dou+投放效果更好'],
    features: ['星图平台', 'dou+投放', '直播变现', '电商导流', '品牌合作'],
    contact: { email: 'creator@douyin.com' },
    audience: '短视频创作者、短剧达人、MCN机构',
    joinTips: '抖音粉丝≥1000可申请星图达人，短剧需通过短剧合作计划入驻',
    commissionRate: '短剧分账 50%-70% + 星图接单',
    bonus: '新达人入驻送dou+投放券',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册抖音账号，完成实名认证' },
      { step: 2, title: '内容定位', description: '确定短剧题材和风格，制定内容计划' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，制作3-5分钟正片' },
      { step: 4, title: '发布上线', description: '在抖音发布短剧，添加话题标签' },
      { step: 5, title: '流量投放', description: '使用dou+投放，提升曝光量' },
      { step: 6, title: '星图接单', description: '粉丝达标后申请星图，接广告合作' },
      { step: 7, title: '分账收益', description: '获得短剧分账和星图接单收益' },
    ],
  },
  {
    id: 'kuaishou-shortdrama',
    name: '快手短剧',
    brand: '快手科技',
    description: '快手是国内第二大短视频平台，短剧内容生态成熟。快手短剧推广达人可加入光合计划获得流量扶持，通过磁力引擎变现。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['都市情感', '农村题材', '甜宠', '逆袭', '玄幻', '搞笑', '悬疑', '家庭伦理', '古装'],
    urls: [
      { label: '快手创作者中心', url: 'https://creator.kuaishou.com/' },
      { label: '磁力引擎', url: 'https://e.kuaishou.com/' },
      { label: '快手短剧官方', url: 'https://www.kuaishou.com/' },
      { label: '快手光合计划', url: 'https://www.kuaishou.com/' },
    ],
    highlights: ['光合计划流量扶持', '磁力引擎变现', '短剧分账', '直播打赏'],
    tips: ['快手用户下沉市场大', '真实感强的内容更受欢迎', '系列短剧粘性高', '配合直播转化效果好'],
    features: ['光合计划', '磁力引擎', '直播变现', '小店导流', '品牌合作'],
    contact: { email: 'creator@kuaishou.com' },
    audience: '下沉市场创作者、短剧达人、MCN机构',
    joinTips: '快手粉丝≥10000可申请光合计划，短剧达人可走专项招募通道',
    commissionRate: '短剧分账 50%-65% + 广告分成',
    bonus: '光合计划新达人送流量扶持',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册快手账号，完成实名认证' },
      { step: 2, title: '内容定位', description: '确定下沉市场题材，贴近真实生活' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重真实感' },
      { step: 4, title: '发布上线', description: '在快手发布短剧，参与话题活动' },
      { step: 5, title: '光合计划', description: '粉丝达标后申请光合计划，获得流量扶持' },
      { step: 6, title: '直播联动', description: '配合直播带货，提升转化效果' },
      { step: 7, title: '分账收益', description: '获得短剧分账和广告分成收益' },
    ],
  },
  {
    id: 'tencent-shortdrama',
    name: '腾讯视频短剧',
    brand: '腾讯',
    description: '腾讯视频是国内头部长视频平台，短剧内容与腾讯生态深度绑定。腾讯视频短剧推广达人可获得微信、QQ、腾讯新闻等多端流量支持。',
    platforms: ['Android', 'iOS', 'Web', '微信小程序'],
    categories: ['都市情感', '古装玄幻', '悬疑推理', '甜宠', '主旋律', '科幻', '漫改', 'IP改编'],
    urls: [
      { label: '腾讯视频创作者平台', url: 'https://v.qq.com/' },
      { label: '腾讯视频号', url: 'https://channels.weixin.qq.com/' },
      { label: '企鹅号', url: 'https://om.qq.com/' },
      { label: '腾讯内容开放平台', url: 'https://om.qq.com/' },
    ],
    highlights: ['腾讯生态多端分发', '微信流量加持', '腾讯广告变现', 'IP影视化机会'],
    tips: ['腾讯视频短剧质量要求较高', 'IP改编类内容有优势', '与微信视频号联动效果佳', '精品化路线更适合'],
    features: ['企鹅号分发', '微信导流', '腾讯广告', 'IP开发', '影视化机会'],
    contact: { email: 'v@tencent.com' },
    audience: '精品短剧创作者、IP改编达人、影视从业者',
    joinTips: '通过腾讯视频创作者平台或企鹅号申请，需提交内容策划方案',
    commissionRate: '短剧分账 50%-75% + 腾讯广告收益',
    bonus: '优质内容获腾讯官方推荐位',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册企鹅号或腾讯视频创作者账号' },
      { step: 2, title: '内容策划', description: '提交短剧策划方案，注重精品化' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑精品短剧，确保制作质量' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架腾讯视频' },
      { step: 5, title: '多端分发', description: '内容分发到微信视频号、QQ等腾讯系产品' },
      { step: 6, title: 'IP开发', description: '优质内容获得影视化IP开发机会' },
      { step: 7, title: '分账收益', description: '获得短剧分账和腾讯广告收益' },
    ],
  },
  {
    id: 'youku-shortdrama',
    name: '优酷短剧',
    brand: '阿里巴巴 / 阿里大文娱',
    description: '优酷是阿里大文娱核心平台，短剧内容与淘宝直播、阿里妈妈广告体系打通。优酷短剧推广达人可借助阿里电商生态实现内容变现。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['都市情感', '古装爱情', '悬疑', '甜宠', '漫改', '喜剧', 'IP改编', '阿里系联名'],
    urls: [
      { label: '优酷创作者平台', url: 'https://creator.youku.com/' },
      { label: '优酷号', url: 'https://mp.youku.com/' },
      { label: '阿里大文娱合作', url: 'https://alibabawenhua.alibaba.com/' },
    ],
    highlights: ['阿里电商联动', '淘宝直播导流', '优酷号分发', '阿里妈妈广告分成'],
    tips: ['与淘宝直播联动可获得额外收益', '阿里妈妈广告分成丰厚', '内容与电商结合变现快', '古装精品内容有优势'],
    features: ['优酷号分发', '淘宝导流', '阿里妈妈广告', '阿里生态联动', 'IP孵化'],
    contact: { email: 'creator@youku.com' },
    audience: '电商+内容创作者、古装短剧达人、阿里系达人',
    joinTips: '通过优酷创作者平台申请，优酷号粉丝≥1000可申请变现',
    commissionRate: '短剧分账 50%-70% + 阿里广告分成',
    bonus: '阿里电商达人入驻送流量券',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册优酷号，登录创作者平台' },
      { step: 2, title: '内容策划', description: '确定短剧题材，结合电商属性' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重古装精品化' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架优酷' },
      { step: 5, title: '淘宝联动', description: '与淘宝直播联动，导流电商' },
      { step: 6, title: '阿里广告', description: '接入阿里妈妈广告，获得分成' },
      { step: 7, title: '多元收益', description: '获得短剧分账+广告分成+电商收益' },
    ],
  },
  {
    id: 'iqiyi-shortdrama',
    name: '爱奇艺短剧',
    brand: '百度 / 爱奇艺',
    description: '爱奇艺是国内领先的长视频平台，短剧内容与爱奇艺文学、百度搜索深度整合。爱奇艺短剧推广达人可借助百度AI技术和搜索流量推广。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['悬疑推理', '都市情感', '玄幻古装', '漫改', 'IP改编', '精品短剧'],
    urls: [
      { label: '爱奇艺号', url: 'https://mp.iqiyi.com/' },
      { label: '爱奇艺号创作者', url: 'https://creator.iqiyi.com/' },
      { label: '爱奇艺文学', url: 'https://wenxue.iqiyi.com/' },
      { label: '百度内容开放平台', url: 'https://baijiahao.baidu.com/' },
    ],
    highlights: ['爱奇艺文学IP联动', '百度搜索流量', 'AI技术加持', '精品内容优先推荐'],
    tips: ['悬疑类内容在爱奇艺表现好', 'IP改编类有优势', '与百度系产品联动可获额外流量', '精品化路线收益更高'],
    features: ['爱奇艺号分发', '百度搜索导流', '文学IP联动', 'AI辅助创作', 'VIP分成'],
    contact: { email: 'creator@iqiyi.com' },
    audience: '悬疑精品创作者、IP改编达人、百度系内容创作者',
    joinTips: '通过爱奇艺号创作者平台申请，需提供内容质量证明',
    commissionRate: '短剧分账 50%-75% + VIP分成',
    bonus: '精品短剧获爱奇艺官方推广资源',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册爱奇艺号，登录创作者平台' },
      { step: 2, title: '内容策划', description: '确定悬疑或IP改编题材，提交策划方案' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑精品短剧，AI辅助创作' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架爱奇艺' },
      { step: 5, title: '搜索导流', description: '借助百度搜索流量，提升曝光' },
      { step: 6, title: '文学联动', description: '与爱奇艺文学IP联动，获得推荐' },
      { step: 7, title: '分账收益', description: '获得短剧分账和VIP分成收益' },
    ],
  },
  {
    id: 'bilibili-shortdrama',
    name: 'B站短剧',
    brand: 'Bilibili / 哔哩哔哩',
    description: 'B站是国内最大的年轻用户社区，短剧内容与B站UP主生态深度结合。B站短剧推广达人可借助B站独特社区文化和年轻用户群体获得高粘性粉丝。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['校园青春', '搞笑', '科幻', '二次元', '都市情感', '悬疑', '漫改', '沙雕', '鬼畜联动'],
    urls: [
      { label: 'B站创作中心', url: 'https://member.bilibili.com/' },
      { label: 'B站UP主合作', url: 'https://www.bilibili.com/' },
      { label: 'B站花火平台', url: 'https://huafa.bilibili.com/' },
      { label: 'B站专栏', url: 'https://member.bilibili.com/v/article' },
    ],
    highlights: ['年轻用户粘性高', '花火平台接单', 'UP主联动', '社区文化氛围浓厚'],
    tips: ['B站用户喜欢有创意的内容', '与UP主联动效果翻倍', '二次元风格受欢迎', '系列内容可建立粉丝粘性'],
    features: ['花火平台', 'UP主联动', '专栏分发', '直播变现', '充电打赏'],
    contact: { email: 'member@bilibili.com' },
    audience: '年轻创作者、二次元达人、UP主、创意短剧作者',
    joinTips: 'B站粉丝≥1000可申请UP主激励计划，短剧达人可申请花火平台接单',
    commissionRate: '花火接单 + 创作激励 + 充电打赏',
    bonus: '新UP主入驻送创作激励金',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册B站账号，成为UP主' },
      { step: 2, title: '内容定位', description: '确定二次元或创意题材，贴合年轻用户' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，加入弹幕互动元素' },
      { step: 4, title: '发布上线', description: '在B站发布短剧，添加标签和分区' },
      { step: 5, title: 'UP主联动', description: '与其他UP主联动，扩大影响力' },
      { step: 6, title: '花火接单', description: '申请花火平台，接品牌合作' },
      { step: 7, title: '多元收益', description: '获得创作激励+花火接单+充电打赏' },
    ],
  },
  {
    id: 'wechat-shortdrama',
    name: '微信短剧',
    brand: '腾讯',
    description: '微信生态拥有海量用户，微信短剧可通过视频号、公众号、小程序等多触点分发。微信短剧推广达人借助微信社交链实现裂变传播。',
    platforms: ['Android', 'iOS', '微信小程序', '视频号'],
    categories: ['都市情感', '职场', '甜宠', '家庭伦理', '逆袭', '微商', '直销', '知识付费联动'],
    urls: [
      { label: '微信视频号', url: 'https://channels.weixin.qq.com/' },
      { label: '公众号平台', url: 'https://mp.weixin.qq.com/' },
      { label: '微信小程序', url: 'https://developers.weixin.qq.com/' },
    ],
    highlights: ['微信社交裂变', '公众号导流', '小程序闭环', '朋友圈传播'],
    tips: ['微信私域流量价值高', '短剧+公众号联动效果佳', '朋友圈分享可带来大量曝光', '小程序可实现付费观看闭环'],
    features: ['视频号分发', '公众号导流', '朋友圈裂变', '小程序付费', '微信广告'],
    contact: { email: 'channels@qq.com' },
    audience: '私域运营达人、公众号创作者、微商转型者',
    joinTips: '微信视频号需实名认证后发布短剧，小程序短剧需通过开发者平台接入',
    commissionRate: '视频号分成 + 小程序付费 + 广告收益',
    bonus: '微信视频号新功能内测资格',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册微信账号，开通视频号' },
      { step: 2, title: '内容策划', description: '确定都市情感或职场题材，贴合私域用户' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重社交传播属性' },
      { step: 4, title: '视频号发布', description: '在视频号发布短剧，引导朋友圈分享' },
      { step: 5, title: '公众号联动', description: '与公众号联动，沉淀私域流量' },
      { step: 6, title: '小程序付费', description: '通过小程序实现付费观看闭环' },
      { step: 7, title: '裂变收益', description: '借助社交裂变，获得视频号分成和小程序收益' },
    ],
  },
  {
    id: 'migu-shortdrama',
    name: '咪咕视频短剧',
    brand: '中国移动 / 咪咕',
    description: '咪咕视频是中国移动旗下平台，拥有运营商独特的用户资源和付费渠道。咪咕短剧推广达人可借助运营商话费支付、积分兑换等独特变现方式。',
    platforms: ['Android', 'iOS', 'Web', '中国移动'],
    categories: ['主旋律', '都市情感', '古装', '军事', '正能量', 'IP改编', '移动用户定制'],
    urls: [
      { label: '咪咕视频创作者', url: 'https://creator.migu.cn/' },
      { label: '咪咕号', url: 'https://www.migu.cn/' },
      { label: '中国移动内容合作', url: 'https://www.chinamobile.com/' },
    ],
    highlights: ['运营商用户资源', '话费支付变现', '积分兑换联动', '移动渠道分发'],
    tips: ['咪咕与移动用户消费习惯匹配', '正能量内容有优势', '运营商活动期间流量大', '移动积分可兑换短剧付费'],
    features: ['运营商分发', '话费支付', '积分兑换', '移动渠道', '主旋律扶持'],
    contact: { email: 'creator@migu.cn' },
    audience: '主旋律创作者、运营商生态达人、正能量内容作者',
    joinTips: '通过咪咕视频创作者平台申请，需提供内容策划方案',
    commissionRate: '短剧分账 50%-70% + 运营商活动奖励',
    bonus: '优质内容获移动渠道额外推广',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册咪咕视频创作者账号' },
      { step: 2, title: '内容策划', description: '确定主旋律或正能量题材，提交策划方案' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，符合移动用户习惯' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架咪咕视频' },
      { step: 5, title: '移动分发', description: '内容分发到中国移动渠道' },
      { step: 6, title: '话费支付', description: '接入话费支付和积分兑换功能' },
      { step: 7, title: '分账收益', description: '获得短剧分账和运营商活动奖励' },
    ],
  },
  {
    id: 'baidu-shortdrama',
    name: '百度好看视频',
    brand: '百度',
    description: '好看视频是百度旗下短视频平台，短剧内容与百度搜索、信息流深度整合。百度好看视频短剧推广达人可借助百度AI技术和搜索流量获得精准用户。',
    platforms: ['Android', 'iOS', 'Web', '百度App'],
    categories: ['都市情感', '玄幻', '悬疑', '搞笑', '知识科普', '历史', '军事'],
    urls: [
      { label: '好看视频创作者', url: 'https://haokan.baidu.com/' },
      { label: '百家号', url: 'https://baijiahao.baidu.com/' },
      { label: '百度内容开放平台', url: 'https://creator.baidu.com/' },
    ],
    highlights: ['百度搜索流量', '百家号联动', '信息流精准推送', 'AI辅助创作'],
    tips: ['百度搜索可带来长尾流量', '百家号+好看视频联动效果佳', '百度AI可辅助脚本创作', '知识类短剧有特色优势'],
    features: ['搜索流量', '百家号分发', '信息流推送', 'AI辅助', '广告分成'],
    contact: { email: 'creator@baidu.com' },
    audience: '知识科普创作者、百度系达人、AI辅助创作达人',
    joinTips: '通过百度内容开放平台申请，百家号+好看视频双平台分发',
    commissionRate: '好看分成 + 百家号收益 + 百度广告',
    bonus: '百度AI创作工具免费使用权',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册百家号，登录百度内容开放平台' },
      { step: 2, title: '内容策划', description: '确定知识科普或实用题材，AI辅助脚本创作' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重信息密度' },
      { step: 4, title: '双平台发布', description: '在百家号和好看视频同步发布' },
      { step: 5, title: '搜索优化', description: '优化标题和标签，获得搜索流量' },
      { step: 6, title: '信息流推送', description: '借助百度信息流精准推送' },
      { step: 7, title: '多元收益', description: '获得好看分成+百家号收益+百度广告' },
    ],
  },
  {
    id: 'toutiao-shortdrama',
    name: '今日头条短剧',
    brand: '字节跳动',
    description: '今日头条是字节跳动旗下资讯平台，短剧内容与抖音、西瓜视频深度打通。头条短剧推广达人可借助字节跳动全矩阵流量实现内容最大化传播。',
    platforms: ['Android', 'iOS', 'Web', '今日头条App'],
    categories: ['都市情感', '三农', '军事', '职场', '情感', '热点改编', '资讯联动'],
    urls: [
      { label: '头条号', url: 'https://mp.toutiao.com/' },
      { label: '今日头条创作者', url: 'https://www.toutiao.com/' },
      { label: '西瓜视频', url: 'https://www.ixigua.com/' },
    ],
    highlights: ['字节跳动矩阵分发', '西瓜视频联动', '头条号变现', '热点内容流量大'],
    tips: ['头条用户偏成熟', '热点结合短剧效果佳', '西瓜视频可发布长版内容', '头条号广告分成丰厚'],
    features: ['头条号分发', '西瓜视频联动', '热点流量', '广告分成', '字节AI工具'],
    contact: { email: 'creator@toutiao.com' },
    audience: '资讯类创作者、三农达人、西瓜视频创作者',
    joinTips: '头条号粉丝≥10000可申请广告分成，西瓜视频联动需单独申请',
    commissionRate: '头条广告分成 + 西瓜分成 + 热点奖金',
    bonus: '热点创作赛奖金，最高万元',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册头条号，登录创作者平台' },
      { step: 2, title: '内容策划', description: '确定资讯类或热点题材，结合社会热点' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重时效性' },
      { step: 4, title: '头条发布', description: '在今日头条发布短剧，参与热点话题' },
      { step: 5, title: '西瓜联动', description: '与西瓜视频联动，发布长版内容' },
      { step: 6, title: '矩阵分发', description: '内容分发到抖音等字节系产品' },
      { step: 7, title: '多元收益', description: '获得头条广告分成+西瓜分成+热点奖金' },
    ],
  },
  {
    id: 'xiaohongshu-shortdrama',
    name: '小红书短剧',
    brand: '小红书',
    description: '小红书是国内最大的种草平台，短剧内容以生活方式、美妆、情感为主，用户粘性极高。小红书短剧推广达人可通过品牌合作、带货等方式变现。',
    platforms: ['Android', 'iOS'],
    categories: ['生活方式', '美妆时尚', '情感', '职场', '美食', '旅行', '家居', '萌宠'],
    urls: [
      { label: '小红书创作者中心', url: 'https://creator.xiaohongshu.com/' },
      { label: '小红书商业合作', url: 'https://www.xiaohongshu.com/' },
      { label: '蒲公英平台', url: 'https://pgy.xiaohongshu.com/' },
    ],
    highlights: ['种草变现强', '品牌合作多', '用户粘性高', '女性用户为主'],
    tips: ['小红书用户喜欢真实感内容', '封面图很重要', '短剧+笔记联动效果佳', '话题标签引流'],
    features: ['蒲公英平台', '品牌合作', '带货变现', '话题引流', '种草内容'],
    contact: { email: 'creator@xiaohongshu.com' },
    audience: '生活方式创作者、美妆达人、女性向内容创作者',
    joinTips: '小红书粉丝≥1000可申请蒲公英平台接单',
    commissionRate: '品牌合作 + 带货佣金',
    bonus: '蒲公英新达人入驻送流量扶持',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册小红书账号，完成实名认证' },
      { step: 2, title: '内容定位', description: '确定生活方式或美妆题材，打造个人风格' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重封面美感' },
      { step: 4, title: '发布笔记', description: '发布短剧+图文笔记，添加话题标签' },
      { step: 5, title: '蒲公英接单', description: '粉丝达标后申请蒲公英平台接品牌合作' },
      { step: 6, title: '种草带货', description: '通过短剧种草，引导商品购买' },
      { step: 7, title: '收益变现', description: '获得品牌合作费用+带货佣金' },
    ],
  },
  {
    id: 'kuaishou-jisu',
    name: '快手极速版短剧',
    brand: '快手科技',
    description: '快手极速版是快手旗下轻量化产品，用户量巨大。快手极速版短剧推广达人可获得额外的极速版流量扶持。',
    platforms: ['Android', 'iOS'],
    categories: ['都市情感', '农村题材', '甜宠', '搞笑', '家庭伦理'],
    urls: [
      { label: '快手极速版', url: 'https://www.kuaishou.com/' },
      { label: '快手创作者中心', url: 'https://creator.kuaishou.com/' },
    ],
    highlights: ['用户量巨大', '极速版流量扶持', '广告分成', '直播联动'],
    tips: ['极速版用户更偏好轻松内容', '短视频短剧更受欢迎', '配合直播转化效果好'],
    features: ['极速版流量', '广告分成', '直播联动', '任务奖励'],
    contact: { email: 'creator@kuaishou.com' },
    audience: '下沉市场创作者、轻松内容达人',
    joinTips: '已入驻快手创作者自动获得极速版分发权限',
    commissionRate: '极速版广告分成 + 任务奖励',
    bonus: '极速版专属流量扶持',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册快手账号，完成实名认证' },
      { step: 2, title: '内容定位', description: '确定轻松搞笑或生活题材，适配极速版用户' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短视频短剧，节奏轻快' },
      { step: 4, title: '同步发布', description: '发布后自动同步到快手极速版' },
      { step: 5, title: '任务参与', description: '参与极速版专属任务，获得奖励' },
      { step: 6, title: '直播联动', description: '配合直播互动，提升转化' },
      { step: 7, title: '收益变现', description: '获得极速版广告分成和任务奖励' },
    ],
  },
  {
    id: 'sogou-shortdrama',
    name: '搜狐视频短剧',
    brand: '搜狐',
    description: '搜狐视频是国内老牌视频平台，短剧内容以自制IP为主。搜狐视频短剧推广达人可获得搜狐矩阵流量支持。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['都市情感', '悬疑', '奇幻', 'IP改编'],
    urls: [
      { label: '搜狐视频', url: 'https://tv.sohu.com/' },
      { label: '搜狐自媒体', url: 'https://mp.sohu.com/' },
    ],
    highlights: ['搜狐矩阵流量', '自制IP机会', '广告分成', '品牌合作'],
    tips: ['搜狐自制IP有优势', '悬疑内容表现好', '配合搜狐新闻联动'],
    features: ['搜狐矩阵', '自制IP', '广告分成', '品牌合作'],
    contact: { email: 'contact@sohu.com' },
    audience: 'IP改编达人、悬疑内容创作者',
    joinTips: '通过搜狐自媒体平台申请，需提交内容策划方案',
    commissionRate: '广告分成 + 内容合作',
    bonus: '优质内容获搜狐首页推荐',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册搜狐自媒体账号，登录创作者平台' },
      { step: 2, title: '内容策划', description: '确定悬疑或IP改编题材，提交策划方案' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重剧情质量' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架搜狐视频' },
      { step: 5, title: '矩阵分发', description: '内容分发到搜狐新闻等搜狐系产品' },
      { step: 6, title: '品牌合作', description: '获得品牌合作和广告分成机会' },
      { step: 7, title: '收益变现', description: '获得广告分成和内容合作收益' },
    ],
  },
  {
    id: 'tencent-mango',
    name: '芒果TV短剧',
    brand: '芒果超媒',
    description: '芒果TV是湖南广电旗下视频平台，短剧内容以青春、偶像、综艺衍生为主。芒果TV短剧推广达人可获得湖南卫视流量支持。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['青春校园', '偶像爱情', '综艺衍生', '都市情感', '古装'],
    urls: [
      { label: '芒果TV', url: 'https://www.mgtv.com/' },
      { label: '芒果创作者中心', url: 'https://creator.mgtv.com/' },
    ],
    highlights: ['湖南卫视流量', '综艺衍生内容', '青春向内容', '粉丝经济'],
    tips: ['芒果TV用户偏年轻', '青春偶像内容受欢迎', '与综艺联动效果佳', '粉丝运营重要'],
    features: ['湖南卫视联动', '综艺衍生', '粉丝运营', '广告分成'],
    contact: { email: 'creator@mgtv.com' },
    audience: '青春内容创作者、偶像题材达人、综艺迷',
    joinTips: '通过芒果创作者中心申请，需提交青春向内容策划',
    commissionRate: '广告分成 + 内容合作',
    bonus: '优质内容获湖南卫视推荐',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册芒果创作者账号，登录创作者中心' },
      { step: 2, title: '内容策划', description: '确定青春偶像或综艺衍生题材，提交策划方案' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重青春气息和颜值' },
      { step: 4, title: '审核上架', description: '提交审核，通过后上架芒果TV' },
      { step: 5, title: '综艺联动', description: '与湖南卫视综艺联动，获得曝光' },
      { step: 6, title: '粉丝运营', description: '运营粉丝社群，提升互动粘性' },
      { step: 7, title: '收益变现', description: '获得广告分成和内容合作收益' },
    ],
  },
  {
    id: 'meitu-shortdrama',
    name: '美图短剧',
    brand: '美图公司',
    description: '美图公司旗下平台，短剧内容以美颜、美妆、时尚为主。美图短剧推广达人可借助美图影像技术创作高质量内容。',
    platforms: ['Android', 'iOS'],
    categories: ['美颜美妆', '时尚穿搭', '情感', '生活方式'],
    urls: [
      { label: '美图秀秀', url: 'https://www.meitu.com/' },
      { label: '美图创作者', url: 'https://creator.meitu.com/' },
    ],
    highlights: ['美图影像技术', '美颜特效丰富', '女性用户为主', '时尚内容'],
    tips: ['美颜特效是特色', '时尚美妆内容受欢迎', '配合美图相机使用', '短视频形式更佳'],
    features: ['美颜特效', '影像技术', '时尚内容', '品牌合作'],
    contact: { email: 'creator@meitu.com' },
    audience: '美妆达人、时尚创作者、美颜爱好者',
    joinTips: '美图创作者平台入驻',
    commissionRate: '品牌合作 + 广告分成',
    bonus: '美图VIP功能免费使用',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册美图创作者账号，登录创作者平台' },
      { step: 2, title: '内容定位', description: '确定美颜美妆或时尚穿搭题材' },
      { step: 3, title: '拍摄制作', description: '使用美图相机拍摄，运用美颜特效' },
      { step: 4, title: '编辑美化', description: '使用美图秀秀美化视频，提升视觉效果' },
      { step: 5, title: '发布上线', description: '在美图平台发布短剧，添加话题标签' },
      { step: 6, title: '品牌合作', description: '获得美妆品牌合作机会' },
      { step: 7, title: '收益变现', description: '获得品牌合作费用和广告分成' },
    ],
  },
  {
    id: 'sina-shortdrama',
    name: '新浪/微博短剧',
    brand: '新浪',
    description: '新浪/微博是国内最大的社交媒体平台之一，短剧内容可通过微博社交链传播。新浪短剧推广达人可获得微博热点流量支持。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['热点改编', '社会话题', '情感', '搞笑', '明星联动'],
    urls: [
      { label: '微博', url: 'https://weibo.com/' },
      { label: '微博视频', url: 'https://video.weibo.com/' },
      { label: '新浪视频', url: 'https://video.sina.com.cn/' },
    ],
    highlights: ['热点流量巨大', '社交传播快', '明星联动', '话题发酵'],
    tips: ['结合热点创作效果佳', '微博话题引流', '明星互动涨粉快', '短视频形式更佳'],
    features: ['热点流量', '社交传播', '明星联动', '话题引流'],
    contact: { email: 'contact@weibo.com' },
    audience: '热点创作者、娱乐达人、明星周边内容作者',
    joinTips: '微博认证后可申请微博视频创作者',
    commissionRate: '广告分成 + 品牌合作',
    bonus: '热点创作赛奖金',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册微博账号，完成实名认证' },
      { step: 2, title: '内容策划', description: '确定热点改编或娱乐题材，结合社会热点' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重时效性和话题性' },
      { step: 4, title: '微博发布', description: '发布短剧，添加热门话题标签' },
      { step: 5, title: '社交传播', description: '引导转发评论，借助社交链传播' },
      { step: 6, title: '明星互动', description: '与明星或大V互动，提升曝光' },
      { step: 7, title: '收益变现', description: '获得广告分成和品牌合作收益' },
    ],
  },
  {
    id: 'tiktok-shortdrama',
    name: 'TikTok 短剧',
    brand: '字节跳动',
    description: 'TikTok是全球最大的短视频平台，短剧内容在全球范围内流行。TikTok短剧推广达人可获得全球流量支持。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['全球流行', '时尚', '美妆', '搞笑', '生活方式', '舞蹈', '挑战'],
    urls: [
      { label: 'TikTok创作者', url: 'https://creator.tiktok.com/' },
      { label: 'TikTok全球', url: 'https://www.tiktok.com/' },
      { label: 'TikTok广告', url: 'https://ads.tiktok.com/' },
    ],
    highlights: ['全球流量', 'TikTok Shop带货', '品牌合作', '全球挑战赛'],
    tips: ['内容需适配全球观众', 'TikTok Shop带货效果好', '音乐很重要', '参与挑战赛涨粉快'],
    features: ['全球分发', 'TikTok Shop', '品牌合作', '挑战赛'],
    contact: { email: 'creator@tiktok.com' },
    audience: '全球内容创作者、时尚达人、跨境电商',
    joinTips: 'TikTok创作者平台入驻，需满足地区要求',
    commissionRate: 'TikTok Shop佣金 + 品牌合作',
    bonus: '全球挑战赛奖金',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册TikTok账号，完成实名认证' },
      { step: 2, title: '内容定位', description: '确定全球流行题材，适配国际观众' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑短剧，注重音乐搭配' },
      { step: 4, title: '全球发布', description: '发布短剧，添加热门音乐和话题' },
      { step: 5, title: '挑战赛参与', description: '参与全球挑战赛，获得曝光' },
      { step: 6, title: 'TikTok Shop', description: '开通TikTok Shop，带货变现' },
      { step: 7, title: '全球收益', description: '获得TikTok Shop佣金和品牌合作收益' },
    ],
  },
  {
    id: 'youtube-shorts',
    name: 'YouTube Shorts',
    brand: 'Google',
    description: 'YouTube是全球最大的视频平台，Shorts是其短视频功能。YouTube Shorts短剧推广达人可获得全球流量和广告分成。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['全球流行', '科技', '教育', '娱乐', '生活方式', '游戏'],
    urls: [
      { label: 'YouTube创作者', url: 'https://studio.youtube.com/' },
      { label: 'YouTube Shorts', url: 'https://www.youtube.com/shorts' },
    ],
    highlights: ['全球最大视频平台', '广告分成高', 'YouTube Partner Program', '频道订阅'],
    tips: ['长视频+Shorts联动效果佳', 'SEO优化很重要', '海外观众偏好真实内容', '广告分成需达标'],
    features: ['全球分发', '广告分成', '频道订阅', 'YouTube Partner'],
    contact: { email: 'creator@youtube.com' },
    audience: '全球创作者、科技达人、教育内容作者',
    joinTips: 'YouTube频道订阅≥1000且观看时长≥4000小时可申请YPP',
    commissionRate: 'YouTube广告分成',
    bonus: 'YouTube Partner Program激励',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册YouTube账号，创建频道' },
      { step: 2, title: '内容定位', description: '确定科技教育或全球流行题材' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑Shorts短剧，配合长视频' },
      { step: 4, title: 'SEO优化', description: '优化标题标签，提升搜索排名' },
      { step: 5, title: '发布上线', description: '发布Shorts，引导订阅频道' },
      { step: 6, title: 'YPP申请', description: '满足条件后申请YouTube Partner Program' },
      { step: 7, title: '全球收益', description: '获得YouTube广告分成收益' },
    ],
  },
  {
    id: 'instagram-reels',
    name: 'Instagram Reels',
    brand: 'Meta',
    description: 'Instagram是全球最大的图片社交平台，Reels是其短视频功能。Instagram Reels短剧推广达人可获得全球流量和品牌合作机会。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['时尚', '美妆', '生活方式', '旅行', '美食', '健身'],
    urls: [
      { label: 'Instagram创作者', url: 'https://business.instagram.com/' },
      { label: 'Instagram Reels', url: 'https://www.instagram.com/' },
    ],
    highlights: ['全球时尚平台', '品牌合作多', 'Instagram Shopping', '视觉内容'],
    tips: ['视觉质量很重要', '时尚美妆内容受欢迎', 'Instagram Shopping带货效果好', '合作品牌多'],
    features: ['全球分发', '品牌合作', 'Instagram Shopping', '视觉内容'],
    contact: { email: 'business@instagram.com' },
    audience: '时尚达人、美妆创作者、生活方式博主',
    joinTips: 'Instagram商业账号注册，粉丝≥1000可申请品牌合作',
    commissionRate: '品牌合作 + Instagram Shopping佣金',
    bonus: 'Instagram新功能内测资格',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册Instagram商业账号' },
      { step: 2, title: '内容定位', description: '确定时尚美妆或生活方式题材' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑Reels短剧，注重视觉美感' },
      { step: 4, title: '发布上线', description: '发布Reels，添加热门音乐和话题' },
      { step: 5, title: 'Shopping开通', description: '开通Instagram Shopping，添加商品标签' },
      { step: 6, title: '品牌合作', description: '获得时尚品牌合作机会' },
      { step: 7, title: '收益变现', description: '获得品牌合作费用和Shopping佣金' },
    ],
  },
  {
    id: 'facebook-reels',
    name: 'Facebook Reels',
    brand: 'Meta',
    description: 'Facebook是全球最大的社交平台，Reels是其短视频功能。Facebook Reels短剧推广达人可获得Meta全家桶流量支持。',
    platforms: ['Android', 'iOS', 'Web'],
    categories: ['生活方式', '社交', '新闻', '娱乐', '品牌内容'],
    urls: [
      { label: 'Facebook创作者', url: 'https://business.facebook.com/' },
      { label: 'Facebook Reels', url: 'https://www.facebook.com/reels' },
    ],
    highlights: ['Meta全家桶流量', 'Facebook Marketplace', '广告分成', '社交传播'],
    tips: ['社交传播快', 'Facebook Marketplace带货', '中老年用户多', '群组引流'],
    features: ['Meta分发', 'Marketplace', '广告分成', '社交传播'],
    contact: { email: 'business@facebook.com' },
    audience: '社交内容创作者、电商达人、中老年向内容作者',
    joinTips: 'Facebook商业账号注册，满足条件可申请广告分成',
    commissionRate: '广告分成 + Marketplace佣金',
    bonus: 'Meta广告优惠券',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册Facebook商业账号' },
      { step: 2, title: '内容定位', description: '确定生活方式或社交题材，适配不同年龄段' },
      { step: 3, title: '拍摄制作', description: '拍摄剪辑Reels短剧，注重社交属性' },
      { step: 4, title: '发布上线', description: '发布Reels，引导群组分享' },
      { step: 5, title: 'Marketplace', description: '开通Facebook Marketplace，带货变现' },
      { step: 6, title: '社交传播', description: '借助Facebook社交链，扩大传播范围' },
      { step: 7, title: '收益变现', description: '获得广告分成和Marketplace佣金' },
    ],
  },
  {
    id: 'netflix-short',
    name: 'Netflix 短剧',
    brand: 'Netflix',
    description: 'Netflix是全球最大的流媒体平台，短剧内容以精品化为主。Netflix短剧推广达人可获得高质量内容曝光机会。',
    platforms: ['Android', 'iOS', 'Web', 'TV'],
    categories: ['精品内容', '悬疑', '科幻', '剧情', 'IP改编'],
    urls: [
      { label: 'Netflix', url: 'https://www.netflix.com/' },
      { label: 'Netflix合作', url: 'https://partnerhelp.netflixstudios.com/' },
    ],
    highlights: ['精品内容平台', '全球分发', '高制作要求', '品牌价值'],
    tips: ['Netflix要求精品化内容', '剧情质量要求高', '适合专业团队', '品牌合作机会'],
    features: ['全球分发', '精品内容', '品牌合作', '高制作标准'],
    contact: { email: 'partners@netflix.com' },
    audience: '专业影视团队、精品内容创作者',
    joinTips: '通过Netflix合作平台申请，需提交高质量内容方案',
    commissionRate: '内容授权 + 合作分成',
    bonus: 'Netflix官方推荐',
    publishFlow: [
      { step: 1, title: '资质审核', description: '提交团队资质和过往作品证明' },
      { step: 2, title: '内容策划', description: '提交精品短剧策划方案，注重剧情深度' },
      { step: 3, title: '立项评估', description: 'Netflix团队评估内容，确定合作意向' },
      { step: 4, title: '拍摄制作', description: '按Netflix标准拍摄制作，确保精品质量' },
      { step: 5, title: '审核上线', description: '提交审核，通过后上架Netflix全球平台' },
      { step: 6, title: '全球分发', description: '内容在全球190+国家和地区分发' },
      { step: 7, title: '收益分成', description: '获得内容授权费用和合作分成' },
    ],
  },
  {
    id: 'disney-short',
    name: 'Disney+ 短剧',
    brand: 'Disney',
    description: 'Disney+是迪士尼旗下流媒体平台，短剧内容以IP衍生为主。Disney+短剧推广达人可获得迪士尼IP授权机会。',
    platforms: ['Android', 'iOS', 'Web', 'TV'],
    categories: ['IP衍生', '动画', '儿童', '家庭', '科幻'],
    urls: [
      { label: 'Disney+', url: 'https://www.disneyplus.com/' },
      { label: 'Disney合作', url: 'https://disneytermsofuse.com/' },
    ],
    highlights: ['迪士尼IP', '家庭向内容', '全球分发', '品牌价值'],
    tips: ['适合家庭向内容', '迪士尼IP授权机会', '动画内容受欢迎', '儿童内容有优势'],
    features: ['IP授权', '家庭内容', '全球分发', '品牌合作'],
    contact: { email: 'partners@disney.com' },
    audience: '动画创作者、家庭内容创作者、IP改编达人',
    joinTips: '通过迪士尼合作平台申请，需提交IP改编方案',
    commissionRate: 'IP授权费用 + 合作分成',
    bonus: '迪士尼IP授权优惠',
    publishFlow: [
      { step: 1, title: '资质审核', description: '提交团队资质和IP改编经验证明' },
      { step: 2, title: 'IP选择', description: '选择迪士尼IP进行改编，提交方案' },
      { step: 3, title: '授权申请', description: '申请迪士尼IP授权，签订合作协议' },
      { step: 4, title: '创作制作', description: '按迪士尼标准创作制作，注重家庭向内容' },
      { step: 5, title: '审核上线', description: '提交审核，通过后上架Disney+' },
      { step: 6, title: '全球分发', description: '内容在全球Disney+平台分发' },
      { step: 7, title: '收益分成', description: '获得IP授权费用和合作分成' },
    ],
  },
  {
    id: 'mcn-yousheng',
    name: '无忧传媒',
    brand: '无忧传媒',
    description: '无忧传媒是国内最大的MCN机构之一，旗下拥有大量头部达人。无忧传媒短剧推广达人可获得专业运营支持和海量资源。',
    platforms: ['抖音', '快手', '小红书', '微博'],
    categories: ['全品类', '娱乐', '生活', '美妆', '美食'],
    urls: [
      { label: '无忧传媒官网', url: 'https://www.wuyou.cn/' },
      { label: '无忧传媒招聘', url: 'https://hr.wuyou.cn/' },
    ],
    highlights: ['头部MCN', '专业运营', '海量资源', '品牌合作'],
    tips: ['无忧传媒门槛较高', '适合有潜力的创作者', '运营支持到位', '变现机会多'],
    features: ['MCN机构', '专业运营', '资源对接', '品牌合作'],
    contact: { email: 'contact@wuyou.cn' },
    audience: '有潜力的创作者、达人',
    joinTips: '通过无忧传媒官网或招聘渠道申请',
    commissionRate: '机构分成 + 个人收益',
    bonus: '签约即获流量扶持',
    publishFlow: [
      { step: 1, title: '报名申请', description: '通过无忧传媒官网或招聘渠道提交申请' },
      { step: 2, title: '面试评估', description: '参加面试，评估创作潜力和风格' },
      { step: 3, title: '签约入驻', description: '签订MCN合作协议，正式入驻' },
      { step: 4, title: '定位规划', description: '运营团队协助制定内容定位和发展规划' },
      { step: 5, title: '资源对接', description: '获得品牌合作资源和流量扶持' },
      { step: 6, title: '专业运营', description: '享受专业运营团队一对一指导' },
      { step: 7, title: '多元变现', description: '获得机构分成和个人收益' },
    ],
  },
  {
    id: 'mcn-kuaishou',
    name: '快手MCN联盟',
    brand: '快手科技',
    description: '快手MCN联盟是快手官方合作的MCN机构联盟，入驻达人可获得快手官方流量扶持。',
    platforms: ['快手', '快手极速版'],
    categories: ['全品类', '农村题材', '生活', '搞笑'],
    urls: [
      { label: '快手MCN合作', url: 'https://www.kuaishou.com/' },
      { label: '快手创作者中心', url: 'https://creator.kuaishou.com/' },
    ],
    highlights: ['快手官方支持', '流量扶持', '任务奖励', '直播联动'],
    tips: ['快手MCN适合下沉市场内容', '直播带货效果好', '任务奖励多'],
    features: ['官方扶持', '流量扶持', '任务奖励', '直播联动'],
    contact: { email: 'mcn@kuaishou.com' },
    audience: '快手创作者、下沉市场达人',
    joinTips: '通过快手创作者中心申请MCN入驻',
    commissionRate: '机构分成 + 官方奖励',
    bonus: '快手官方流量扶持',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册快手账号，完成实名认证' },
      { step: 2, title: 'MCN申请', description: '通过快手创作者中心申请MCN联盟入驻' },
      { step: 3, title: '审核通过', description: '提交资质审核，通过后正式入驻' },
      { step: 4, title: '官方扶持', description: '获得快手官方流量扶持和任务奖励' },
      { step: 5, title: '内容创作', description: '创作下沉市场题材短剧' },
      { step: 6, title: '直播联动', description: '配合直播带货，提升转化效果' },
      { step: 7, title: '收益变现', description: '获得机构分成和官方奖励' },
    ],
  },
  {
    id: 'mcn-douyin',
    name: '抖音MCN联盟',
    brand: '字节跳动',
    description: '抖音MCN联盟是抖音官方合作的MCN机构联盟，入驻达人可获得抖音官方流量扶持和商业化机会。',
    platforms: ['抖音', '抖音极速版', 'TikTok'],
    categories: ['全品类', '娱乐', '美妆', '时尚', '生活'],
    urls: [
      { label: '抖音MCN合作', url: 'https://www.douyin.com/' },
      { label: '巨量星图', url: 'https://www.xingtaodata.com/' },
    ],
    highlights: ['抖音官方支持', '巨量星图接单', '流量扶持', '商业化机会'],
    tips: ['抖音MCN门槛较高', '适合优质内容创作者', '星图接单机会多', '流量扶持大'],
    features: ['官方扶持', '星图接单', '流量扶持', '商业化'],
    contact: { email: 'mcn@douyin.com' },
    audience: '抖音创作者、优质内容达人',
    joinTips: '通过巨量星图或抖音创作者中心申请',
    commissionRate: '机构分成 + 星图收益',
    bonus: '抖音官方流量扶持',
    publishFlow: [
      { step: 1, title: '账号注册', description: '注册抖音账号，完成实名认证' },
      { step: 2, title: 'MCN申请', description: '通过巨量星图或抖音创作者中心申请MCN联盟' },
      { step: 3, title: '审核通过', description: '提交资质审核，通过后正式入驻' },
      { step: 4, title: '官方扶持', description: '获得抖音官方流量扶持和商业化机会' },
      { step: 5, title: '星图接单', description: '入驻星图平台，接品牌合作订单' },
      { step: 6, title: '内容创作', description: '创作优质短剧内容，配合dou+投放' },
      { step: 7, title: '收益变现', description: '获得机构分成和星图收益' },
    ],
  },
];
